### ISSUE TITLE
"Orb" subsurface shader crashes under iOS16

### ISSUE THREAD

**Issue by gordonbrander** [subconsciousnetwork/subconscious#376]
```log
2022-11-08 08:59:44.420798-0500 Subconscious[526:9956] Metal GPU Frame Capture Enabled
2022-11-08 08:59:44.421290-0500 Subconscious[526:9956] Metal API Validation Enabled
2022-11-08 08:59:44.482445-0500 Subconscious[526:9956] Errors found! Invalidating cache...
2022-11-08 08:59:44.499726-0500 Subconscious[526:9956] Errors found! Invalidating cache...
2022-11-08 08:59:44.560001-0500 Subconscious[526:9956] [Metal Compiler Warning] Warning: Compilation succeeded with: 

program_source:179:19: warning: unused variable 'midpoint_xy'
    metal::float2 midpoint_xy = 0.5 * resolution;
                  ^
program_source:202:11: warning: unused variable 'ttt'
    float ttt = metal::clamp(_e75 + 0.10000000149011612, 0.0, 1.0);
          ^
program_source:213:11: warning: unused variable 'occlusion_alpha'
    float occlusion_alpha = (_e160 * _e160) * 0.8500000238418579;
          ^
2022-11-08 08:59:44.562379-0500 Subconscious[526:9956] [Metal Compiler Warning] Warning: Compilation succeeded with: 

program_source:179:19: warning: unused variable 'midpoint_xy'
    metal::float2 midpoint_xy = 0.5 * resolution;
                  ^
program_source:202:11: warning: unused variable 'ttt'
    float ttt = metal::clamp(_e75 + 0.10000000149011612, 0.0, 1.0);
          ^
program_source:213:11: warning: unused variable 'occlusion_alpha'
    float occlusion_alpha = (_e160 * _e160) * 0.8500000238418579;
          ^
thread '<unnamed>' panicked at 'overflow when subtracting duration from instant', library/std/src/time.rs:425:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
libc++abi: terminating with uncaught foreign exception
terminating with uncaught foreign exception
```

**Comment by bfollington** [comment]
Possible workaround: convert WGSL to Metal shader with https://github.com/gfx-rs/naga to retain single source of truth.

**Comment by jsantell** [comment]
Would be interested in seeing what the backtrace for something like this is, the expectation is [pretty explicit](https://doc.rust-lang.org/src/std/time.rs.html#424) and fixable, but is in some dependency, TBD how deep.

```
thread '<unnamed>' panicked at 'overflow when subtracting duration from instant', library/std/src/time.rs:425:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
